security:
    password_hashers:
        App\Entity\Users:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            user_checker: App\Security\UserChecker
            
            custom_authenticators:
                - App\Security\AppCustomAuthenticator
                - App\Security\GoogleAuthenticator
            
            entry_point: App\Security\AppCustomAuthenticator
            
            logout:
                path: app_logout
                target: /welcome

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        - { path: ^/welcome, roles: PUBLIC_ACCESS }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google, roles: PUBLIC_ACCESS }
        - { path: ^/choose-role, roles: IS_AUTHENTICATED_FULLY }
        - { path: ^/set-role, roles: IS_AUTHENTICATED_FULLY }

when@test:
    security:
        password_hashers:
            App\Entity\Users:
                algorithm: plaintext